---
name: graduation_project
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  google_nav_bar: ^5.0.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  flutter_svg: ^1.1.6
  line_awesome_flutter: ^2.0.0
  gsheets: ^0.4.2
  intl: any
  provider: ^6.0.5
  path_provider: ^2.0.13
  image_picker: ^0.8.6+3
  get: ^4.6.5
  multi_select_flutter: ^4.1.3
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.1.0
  firebase_storage: ^11.1.1
  jiffy: ^5.0.0
  cached_network_image: ^3.2.3
  conditional_builder_null_safety: ^0.0.6

  fluttertoast: ^8.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/account.png
    - assets/gifs/
    - assets/images/lab.jpg
    - assets/images/radiology.jpg
    - assets/images/doctor.jpg
    - assets/images/Anim1.jpg
    - assets/images/Anim2.jpg
    - assets/images/Anim3.jpg
    - assets/images/Anim4.jpg
    - assets/images/alfaLAB.jpg
    - assets/images/almokhtaber.jpg
    - assets/images/elfouadLAB.jpg
    - assets/images/elfouadCENTER.jpg
    - assets/images/samascan.jpg
    - assets/images/ahmedFarid.jpeg
    - assets/images/welcome.jpg
    - assets/images/logo.png
  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf
  - family: Playfair Display
    fonts:
    - asset: fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
  - family: Itim
    fonts:
    - asset: fonts/Itim-Regular.ttf
  - family: Archivo
    fonts:
    - asset: fonts/Archivo-Regular.ttf
